create_product:
    path: /products
    defaults:
        _controller: ApiBundle:Product:create
    methods: [POST]

get_product:
    path: /products/{id}
    defaults:
        _controller: ApiBundle:Product:get
    methods: [GET]

update_product:
    path: /products/{id}
    defaults:
        _controller: ApiBundle:Product:update
    methods: [PATCH]