# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    shop.service.uuid_generator:
        class: Shop\Common\Service\UuidGenerator

    shop.product.command_handler:
        class: Shop\Product\ProductCommandHandler
        arguments: ['@shop.product.repository']
        tags:
            - { name: command_handler }

    shop.product.repository:
        class: Shop\Product\Repository
        arguments: ['@broadway.event_store', '@broadway.event_handling.event_bus']

#    shop.product.read_model.projector:
#        class: Shop\Product\Projector\ProductProjector
#        arguments: ['@shop.product.read_model.repository']
#        tags:
#            - { name: broadway.domain.event_listener }
#
#    shop.product.read_model.repository:
#        class: 'Broadway\ReadModel\ReadModel'
#        factory: 'broadway.read_model.elasticsearch.repository_factory:create'
#        arguments: ['shop.product', 'Shop\Product\ReadModel\Product']
#        tags:
#            - { name: read_model_repository }